steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      set -e
      git fetch --tags --unshallow || git fetch --tags
      echo "Tag Received: ${TAG_NAME}"
    
  - name: 'gcr.io/cloud-builders/git'
    id: detect-changes
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        _CURRENT_TAG="${TAG_NAME}"
        _CURRENT_SHA=$(echo "$_CURRENT_TAG" | sed 's/^prod_//')
        echo "Current SHA: $_CURRENT_SHA"

        # # Find the previous prod tag (exclude current)
        # _PREVIOUS_TAG=$(git tag --sort=-version:refname \
        #   | grep "^prod_" \
        #   | grep -v "^${_CURRENT_TAG}$" \
        #   | head -1)

        # echo "Previous prod tag: $_PREVIOUS_TAG"

options:
  logging: CLOUD_LOGGING_ONLY